In [1]:
import pandas as pd
from IPython.core.display import display

In [2]:
STATIONS = pd.read_csv('STATIONS.csv', index_col = 0);
DLY_LEVELS = pd.read_csv('DLY_LEVELS.csv')
DLY_FLOWS = pd.read_csv('DLY_FLOWS.csv')

print("    Stations in the HYDAT database = ", len(STATIONS.index))

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

    Stations in the HYDAT database =  7828

In [3]:
# bounding region
lngW = -85.
lngE = -75.
latS = 41.
latN = 44.

In [4]:
# locate monitoring stations within bounding region
stationList = STATIONS[(STATIONS['LATITUDE'] >= latS) & \
         (STATIONS['LATITUDE'] <= latN) & \
         (STATIONS['LONGITUDE'] <= lngE) & \
         (STATIONS['LONGITUDE'] >= lngW)].STATION_NUMBER.values

In [5]:
# reduce data sets to the area of interest
WSC_STATIONS = STATIONS[STATIONS.STATION_NUMBER.isin(stationList)]
DLY_LEVELS = DLY_LEVELS[DLY_LEVELS.STATION_NUMBER.isin(stationList)]
DLY_FLOWS = DLY_FLOWS[DLY_FLOWS.STATION_NUMBER.isin(stationList)]

In [34]:
DLY_FLOWS = DLY_FLOWS[DLY_FLOWS.YEAR>1995]

In [35]:
# add columns to STATIONS for level and flow stations
WSC_STATIONS['Level'] = ''
WSC_STATIONS['Flow'] = ''

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [36]:
# mark level and flow stations
WSC_STATIONS.loc[WSC_STATIONS.STATION_NUMBER.isin(DLY_LEVELS.STATION_NUMBER), "Level"] = True
WSC_STATIONS.loc[WSC_STATIONS.STATION_NUMBER.isin(DLY_FLOWS.STATION_NUMBER), "Flow"] = True

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [37]:
print("Stations within region of interest = ", len(WSC_STATIONS.index))
print("DLY_FLOWS records = ", len(DLY_FLOWS.index))
print("DLY_LEVELS records = ", len(DLY_LEVELS.index))
display(WSC_STATIONS.ix[:,['Level','Flow','STATION_NAME','LATITUDE','LONGITUDE',]])

WSC_STATIONS.to_pickle('data/WSC_STATIONS')

Stations within region of interest =  319
DLY_FLOWS records =  37247
DLY_LEVELS records =  47875

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.

,Level,Flow,STATION_NAME,LATITUDE,LONGITUDE
688,True,True,LUCKNOW RIVER AT LUCKNOW,43.965279,-81.513443
690,,,MAITLAND RIVER AT BENMILLER,43.718059,-81.626389
691,True,True,MAITLAND RIVER BELOW WINGHAM,43.886749,-81.326439
692,True,True,MIDDLE MAITLAND RIVER NEAR LISTOWEL,43.727230,-80.972671
693,,,MAITLAND RIVER NEAR DONNYBROOK,43.825001,-81.490562
694,True,True,MAITLAND RIVER ABOVE WINGHAM,43.915081,-81.264389
695,True,True,LITTLE MAITLAND RIVER AT BLUEVALE,43.854389,-81.250504
696,True,True,MIDDLE MAITLAND RIVER NEAR BELGRAVE,43.812889,-81.306892
697,True,True,SOUTH MAITLAND RIVER AT SUMMERHILL,43.684360,-81.541168
698,True,True,BOYLE DRAIN NEAR ATWOOD,43.676338,-81.074852
699,True,True,MAITLAND RIVER NEAR HARRISTON,43.903809,-80.892609
700,True,,LAKE HURON AT GODERICH,43.745392,-81.727814
701,True,True,MIDDLE MAITLAND RIVER ABOVE ETHEL,43.718391,-81.124641
702,True,True,BLYTH BROOK BELOW BLYTH,43.760330,-81.463188
703,True,True,MAITLAND RIVER AT BENMILLER,43.717560,-81.626190
704,True,True,SOUTH MAITLAND RIVER AT ROXBORO,43.579250,-81.401314
705,True,True,LAKELET CREEK NEAR GORRIE,43.892921,-81.063278
706,True,,BLIND CREEK NEAR FORDWICH,43.894730,-81.037331
707,,,AUSABLE RIVER NEAR ARKONA,43.077782,-81.796112
708,True,True,AUSABLE RIVER NEAR SPRINGBANK,43.071919,-81.659752
709,,,PARKHILL CREEK NEAR PARKHILL,43.169720,-81.683327
710,True,True,SOUTH PARKHILL CREEK NEAR PARKHILL,43.160751,-81.731827
711,,,MORAY CREEK NEAR PARKHILL,43.216671,-81.745560
712,,,SHIPKA CREEK NEAR GRAND BEND,43.271938,-81.750000
713,True,True,BAYFIELD RIVER NEAR VARNA,43.551251,-81.589531
714,True,True,PARKHILL CREEK ABOVE PARKHILL RESERVOIR,43.164131,-81.631508
715,True,True,AUSABLE RIVER NEAR EXETER,43.361969,-81.509438
716,True,,AUSABLE RIVER NEAR PARKHILL,43.193390,-81.814499
717,True,True,SILVER CREEK AT SEAFORTH,43.545361,-81.396362
718,True,True,PERCH CREEK AT SARNIA,42.984081,-82.318748
...,...,...,...,...,...
979,True,True,CENTREVILLE CREEK NEAR ALBION,43.924439,-79.834442
980,True,True,LITTLE ROUGE RIVER NEAR DICKSONS HILL,43.925690,-79.282188
981,True,True,LYNDE CREEK AT BROOKLIN,43.959080,-78.959969
982,True,True,LYNDE CREEK TRIBUTARY NEAR KINSALE,43.931969,-78.988472
983,True,True,DON RIVER EAST BRANCH NEAR THORNHILL,43.826611,-79.438080
984,True,True,HUMBER RIVER NEAR BALLYCROY,43.970310,-79.887718
985,True,True,WEST HIGHLAND CREEK NEAR SCARBOROUGH VILLAGE,43.753220,-79.233673
986,True,True,HUMBER RIVER AT HIGHWAY NO. 9,43.968769,-79.873741
987,,,ROUGE RIVER AT SCARBOROUGH,43.811111,-79.159721
988,,,LITTLE ROUGE CREEK AT SCARBOROUGH,43.813889,-79.156937
989,,,PETTICOAT CREEK NEAR DUNBARTON,43.834721,-79.148613
990,,,WEST DUFFINS CREEK NEAR PICKERING,43.849998,-79.086670
991,,,GANATSEKIAGON CREEK NEAR PICKERING,43.859718,-79.086113
992,,,GANARASKA RIVER AT PORT HOPE,43.968330,-78.295281
993,,,GANARASKA RIVER NEAR DALE,43.985279,-78.301666
996,True,True,BOWMANVILLE CREEK AT BOWMANVILLE,43.921471,-78.702004
997,,,SOPER CREEK AT BOWMANVILLE,43.902222,-78.672501
998,True,True,OSHAWA CREEK AT OSHAWA,43.930309,-78.891533
999,True,True,WILMOT CREEK NEAR NEWCASTLE,43.930222,-78.618813
1000,True,True,SHELTER VALLEY BROOK NEAR GRAFTON,43.991878,-78.001221
1001,True,True,GANARASKA RIVER ABOVE DALE,43.990940,-78.328194
1002,True,True,HARMONY CREEK AT OSHAWA,43.888859,-78.824944
1003,,,FAREWELL CREEK AT OSHAWA,43.888329,-78.821114
1004,True,,LAKE ONTARIO AT COBOURG,43.956471,-78.164391
1006,True,True,COBOURG BROOK AT COBOURG,43.964871,-78.184807
1009,True,True,COBOURG BROOK NEAR PRECIOUS CORNERS,43.988430,-78.210648
1010,True,True,MACKIE CREEK NEAR HAMPTON,43.979080,-78.680313
1011,True,True,GAGE CREEK NEAR DALE,43.997028,-78.254334
1012,,,BLOOMFIELD CREEK AT BLOOMFIELD,43.990559,-77.218330
1015,True,True,BLACK CREEK AT MILFORD,43.935360,-77.090210

In [82]:
def getFlowsWSC(s):
#     s = [s for s in WSC_STATIONS[WSC_STATIONS['Flow']==True].STATION_NUMBER][0]
    ts = {}
    data = DLY_FLOWS[DLY_FLOWS['STATION_NUMBER'] == s]
    for k in data.index:
            mo = str(data.ix[k,'MONTH'])
            yr = str(data.ix[k,'YEAR'])
            for n in range(1,data.ix[k,'NO_DAYS']+1):
#                 print(data.ix[k])
#                 print(float(data.ix[k,'FLOW'+str(n)]))
                ts[pd.to_datetime(yr+'-'+mo+'-'+str(n))] = data.ix[k,'FLOW'+str(n)]
                
    ts = pd.Series(ts)
    ts.name = str(s) +': ' + STATIONS[STATIONS['STATION_NUMBER']==s].STATION_NAME.values[0] + \
            ' from ' + '{0}'.format(ts.index[0].year) + \
            ' to ' + '{0}'.format(ts.index[-1].year)
#     #drop initial and terminal null entries
#     j = 0
#     while j<len(ts.index) and pd.isnull(ts.ix[j]):
#         j += 1
#     k = len(ts.index) - 1
#     while k>=j and pd.isnull(ts.ix[k]):
#         k += -1
#     return ts[j:k+1]
    return ts

WSC_FLOWS = pd.DataFrame({s: getFlowsWSC(s) for s in WSC_STATIONS[WSC_STATIONS['Flow']==True].STATION_NUMBER})
WSC_FLOWS.to_pickle('data/WSC_FLOWS')
WSC_FLOWS.tail()

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys
/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

/Users/imarkelo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()

,02FD002,02FE002,02FE003,02FE005,02FE007,02FE008,02FE009,02FE010,02FE011,02FE013,...,02HD008,02HD009,02HD010,02HD012,02HD013,02HD019,02HD022,02HD023,02HD024,02HE004
2017-12-27,0.826,22.100000,0.389,5.85,3.14,6.12,3.91,1.190,0.857,2.43,...,0.908,0.780,0.548,2.31,NaN,0.859,0.261,0.182,0.178,0.396
2017-12-28,0.686,24.299999,0.424,5.79,3.25,5.97,4.83,1.120,0.835,2.09,...,0.764,0.776,0.531,2.29,NaN,0.817,0.245,0.177,0.176,0.362
2017-12-29,0.558,20.700001,0.444,5.26,2.83,4.27,3.62,1.060,0.817,1.95,...,0.719,0.771,0.517,2.27,NaN,0.781,0.231,0.174,0.174,0.350
2017-12-30,0.522,17.200001,0.450,4.98,2.65,3.88,3.22,1.020,0.803,1.87,...,0.729,0.767,0.504,2.27,NaN,0.750,0.220,0.172,0.173,0.333
2017-12-31,0.529,14.900000,0.348,4.77,2.53,3.60,3.01,0.987,0.791,1.80,...,0.747,0.763,0.492,2.26,NaN,0.722,0.211,0.165,0.172,0.326