In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

sns.set_style("whitegrid")
plt.rcParams.update({'font.size': 32})
sns.set_context("poster", rc={"font.size":34,"axes.titlesize":34,"axes.labelsize":34, "lines.linewidth": 2})  
plt.rcParams['figure.figsize'] = 18, 12


from datetime import datetime
str(datetime.now())

'2018-08-13 15:49:55.548568'

In [2]:
df = pd.read_csv('../../measurements/GLNPO/GLENDA PO4.csv')

In [3]:
df.groupby(['STATION_ID']).count()

,Row,YEAR,MONTH,SEASON,LAKE,CRUISE_ID,VISIT_ID,STN_DEPTH_M,LATITUDE,LONGITUDE,...,METHOD_1,RESULT_REMARK_1,ANL_CODE_2,ANALYTE_2,VALUE_2,UNITS_2,FRACTION_2,METHOD_2,RESULT_REMARK_2,Unnamed: 33
STATION_ID,,,,,,,,,,,,,,,,,,,,,
ER01,4,4,4,4,4,0,4,4,4,4,...,4,0,0,0,0,0,0,0,0,0
ER09,265,265,265,239,265,17,265,29,29,29,...,265,11,0,0,0,0,0,0,0,0
ER09H8501,1,1,1,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ER09H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER10,182,182,182,175,182,17,182,27,27,27,...,182,9,0,0,0,0,0,0,0,0
ER15H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER15H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER15H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER15M,423,423,423,376,423,31,423,50,50,50,...,423,27,0,0,0,0,0,0,0,0
ER18,72,72,72,56,72,0,72,0,0,0,...,72,3,0,0,0,0,0,0,0,0
ER18H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER18H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER18H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER30,159,159,159,152,159,14,159,23,23,23,...,159,13,0,0,0,0,0,0,0,0
ER31,164,164,164,157,164,13,164,22,22,22,...,164,9,0,0,0,0,0,0,0,0
ER32,157,157,157,150,157,13,157,23,23,23,...,157,8,0,0,0,0,0,0,0,0
ER36,168,168,168,160,168,12,168,22,22,22,...,168,13,0,0,0,0,0,0,0,0
ER37,229,229,229,207,229,12,229,21,21,21,...,229,17,1,1,1,1,1,1,0,0
ER38,163,163,163,156,163,16,163,25,25,25,...,163,7,0,0,0,0,0,0,0,0
ER42,228,228,228,206,228,13,228,23,23,23,...,228,6,0,0,0,0,0,0,0,0
ER43,169,169,169,161,169,12,169,22,22,22,...,169,13,0,0,0,0,0,0,0,0
ER55,60,60,60,45,60,0,60,0,0,0,...,60,1,0,0,0,0,0,0,0,0
ER55H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER55H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER55H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER57,72,72,72,54,72,0,72,0,0,0,...,72,1,0,0,0,0,0,0,0,0
ER57H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER57H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER57H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER58,93,93,93,93,93,12,93,21,21,21,...,93,0,3,3,3,3,3,3,0,0
ER59,95,95,95,95,95,13,95,23,23,23,...,95,2,0,0,0,0,0,0,0,0
ER60,152,152,152,140,152,15,152,25,25,25,...,152,4,0,0,0,0,0,0,0,0
ER60H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER60H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER60H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER61,96,96,96,96,96,13,96,21,21,21,...,96,1,0,0,0,0,0,0,0,0
ER63,192,192,192,185,192,19,192,31,31,31,...,192,11,0,0,0,0,0,0,0,0
ER73,220,220,220,198,220,12,220,21,21,21,...,220,11,0,0,0,0,0,0,0,0
ER73H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER73H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER73H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER78H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER78H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER78H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER78M,270,270,270,239,270,18,270,30,30,30,...,270,15,0,0,0,0,0,0,0,0
ER79,55,55,55,43,55,0,55,0,0,0,...,55,0,0,0,0,0,0,0,0,0
ER79H,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER79H8501,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER79H8502,2,2,2,0,2,0,2,0,0,0,...,2,0,0,0,0,0,0,0,0,0
ER91M,99,99,99,99,99,14,99,23,23,23,...,99,4,0,0,0,0,0,0,0,0
ER92,96,96,96,96,96,13,96,23,23,23,...,96,1,0,0,0,0,0,0,0,0
ERFE,7,7,7,7,7,7,7,7,7,7,...,7,0,0,0,0,0,0,0,0,0

In [4]:
df[df['STATION_ID']=='ER15M'].groupby(['YEAR', 'MONTH', 'SAMPLE_DEPTH_M']).count()

                               Row  SEASON  LAKE  CRUISE_ID  VISIT_ID  \
YEAR MONTH     SAMPLE_DEPTH_M
1983 April     0.91              2       2     2          0         2
               4.27              2       2     2          0         2
               10.06             2       2     2          0         2
               18.90             1       1     1          0         1
               19.20             1       1     1          0         1
               29.57             1       1     1          0         1
               29.87             1       1     1          0         1
               39.93             1       1     1          0         1
               40.23             1       1     1          0         1
               48.77             1       1     1          0         1
               49.68             1       1     1          0         1
               56.39             1       1     1          0         1
               57.61             1       1     1          0         1
     August    0.91              3       3     3          0         3
               4.57              2       2     2          0         2
               4.88              1       1     1          0         1
               10.06             3       3     3          0         3
               17.37             1       1     1          0         1
               20.12             1       1     1          0         1
               22.25             1       1     1          0         1
               29.26             1       1     1          0         1
               29.87             1       1     1          0         1
               39.62             1       1     1          0         1
               39.93             1       1     1          0         1
               40.23             1       1     1          0         1
               49.68             1       1     1          0         1
               50.29             1       1     1          0         1
               51.21             1       1     1          0         1
               57.00             1       1     1          0         1
               58.22             2       2     2          0         2
...                            ...     ...   ...        ...       ...
1996 April     30.00             2       2     2          0         2
               40.00             3       3     3          0         3
               52.00             2       2     2          0         2
               60.00             1       1     1          0         1
               61.00             1       1     1          0         1
2016 April     2.10              1       1     1          1         1
               5.00              1       1     1          1         1
               10.00             2       2     2          2         2
               20.00             1       1     1          1         1
               30.00             1       1     1          1         1
               40.10             1       1     1          1         1
               53.00             1       1     1          1         1
               62.00             1       1     1          1         1
     August    2.00              1       1     1          1         1
               7.00              1       1     1          1         1
               14.00             1       1     1          1         1
               19.00             1       1     1          1         1
               25.50             1       1     1          1         1
               28.10             1       1     1          1         1
               40.00             1       1     1          1         1
               52.00             1       1     1          1         1
               61.10             1       1     1          1         1
2017 April     2.20              1       1     1          1         1
               5.20              1       1     1          1         1
               10.10             2       2     2          2         2
               20.20             1       1     1          1         1
               30.10             1       1     1          1         1
               40.20             1       1     1          1         1
               52.10             1       1     1          1         1
               60.40             1       1     1          1         1

                               STATION_ID  STN_DEPTH_M  LATITUDE  LONGITUDE  \
YEAR MONTH     SAMPLE_DEPTH_M
1983 April     0.91                     2            0         0          0
               4.27                     2            0         0          0
               10.06                    2            0         0          0
               18.90                    1            0         0          0
               19.20                    1            0         0          0
               29.57                    1            0         0          0
               29.87                    1            0         0          0
               39.93                    1            0         0          0
               40.23                    1            0         0          0
               48.77                    1            0         0          0
               49.68                    1            0         0          0
               56.39                    1            0         0          0
               57.61                    1            0         0          0
     August    0.91                     3            0         0          0
               4.57                     2            0         0          0
               4.88                     1            0         0          0
               10.06                    3            0         0          0
               17.37                    1            0         0          0
               20.12                    1            0         0          0
               22.25                    1            0         0          0
               29.26                    1            0         0          0
               29.87                    1            0         0          0
               39.62                    1            0         0          0
               39.93                    1            0         0          0
               40.23                    1            0         0          0
               49.68                    1            0         0          0
               50.29                    1            0         0          0
               51.21                    1            0         0          0
               57.00                    1            0         0          0
               58.22                    2            0         0          0
...                                   ...          ...       ...        ...
1996 April     30.00                    2            2         2          2
               40.00                    3            3         3          3
               52.00                    2            2         2          2
               60.00                    1            1         1          1
               61.00                    1            1         1          1
2016 April     2.10                     1            1         1          1
               5.00                     1            1         1          1
               10.00                    2            2         2          2
               20.00                    1            1         1          1
               30.00                    1            1         1          1
               40.10                    1            1         1          1
               53.00                    1            1         1          1
               62.00                    1            1         1          1
     August    2.00                     1            1         1          1
               7.00                     1            1         1          1
               14.00                    1            1         1          1
               19.00                    1            1         1          1
               25.50                    1            1         1          1
               28.10                    1            1         1          1
               40.00                    1            1         1          1
               52.00                    1            1         1          1
               61.10                    1            1         1          1
2017 April     2.20                     1            1         1          1
               5.20                     1            1         1          1
               10.10                    2            2         2          2
               20.20                    1            1         1          1
               30.10                    1            1         1          1
               40.20                    1            1         1          1
               52.10                    1            1         1          1
               60.40                    1            1         1          1

                               SAMPLING_DATE     ...       METHOD_1  \
YEAR MONTH     SAMPLE_DEPTH_M                    ...
1983 April     0.91                        2     ...              2
               4.27                        2     ...              2
               10.06                       2     ...              2
               18.90                       1     ...              1
               19.20                       1     ...              1
               29.57                       1     ...              1
               29.87                       1     ...              1
               39.93                       1     ...              1
               40.23                       1     ...              1
               48.77                       1     ...              1
               49.68                       1     ...              1
               56.39                       1     ...              1
               57.61                       1     ...              1
     August    0.91                        3     ...              3
               4.57                        2     ...              2
               4.88                        1     ...              1
               10.06                       3     ...              3
               17.37                       1     ...              1
               20.12                       1     ...              1
               22.25                       1     ...              1
               29.26                       1     ...              1
               29.87                       1     ...              1
               39.62                       1     ...              1
               39.93                       1     ...              1
               40.23                       1     ...              1
               49.68                       1     ...              1
               50.29                       1     ...              1
               51.21                       1     ...              1
               57.00                       1     ...              1
               58.22                       2     ...              2
...                                      ...     ...            ...
1996 April     30.00                       2     ...              2
               40.00                       3     ...              3
               52.00                       2     ...              2
               60.00                       1     ...              1
               61.00                       1     ...              1
2016 April     2.10                        1     ...              1
               5.00                        1     ...              1
               10.00                       2     ...              2
               20.00                       1     ...              1
               30.00                       1     ...              1
               40.10                       1     ...              1
               53.00                       1     ...              1
               62.00                       1     ...              1
     August    2.00                        1     ...              1
               7.00                        1     ...              1
               14.00                       1     ...              1
               19.00                       1     ...              1
               25.50                       1     ...              1
               28.10                       1     ...              1
               40.00                       1     ...              1
               52.00                       1     ...              1
               61.10                       1     ...              1
2017 April     2.20                        1     ...              1
               5.20                        1     ...              1
               10.10                       2     ...              2
               20.20                       1     ...              1
               30.10                       1     ...              1
               40.20                       1     ...              1
               52.10                       1     ...              1
               60.40                       1     ...              1

                               RESULT_REMARK_1  ANL_CODE_2  ANALYTE_2  \
YEAR MONTH     SAMPLE_DEPTH_M
1983 April     0.91                          1           0          0
               4.27                          0           0          0
               10.06                         0           0          0
               18.90                         0           0          0
               19.20                         0           0          0
               29.57                         0           0          0
               29.87                         0           0          0
               39.93                         0           0          0
               40.23                         0           0          0
               48.77                         0           0          0
               49.68                         0           0          0
               56.39                         0           0          0
               57.61                         0           0          0
     August    0.91                          0           0          0
               4.57                          0           0          0
               4.88                          0           0          0
               10.06                         0           0          0
               17.37                         0           0          0
               20.12                         0           0          0
               22.25                         0           0          0
               29.26                         0           0          0
               29.87                         0           0          0
               39.62                         0           0          0
               39.93                         0           0          0
               40.23                         0           0          0
               49.68                         0           0          0
               50.29                         0           0          0
               51.21                         0           0          0
               57.00                         0           0          0
               58.22                         0           0          0
...                                        ...         ...        ...
1996 April     30.00                         0           0          0
               40.00                         0           0          0
               52.00                         0           0          0
               60.00                         0           0          0
               61.00                         0           0          0
2016 April     2.10                          1           0          0
               5.00                          1           0          0
               10.00                         2           0          0
               20.00                         1           0          0
               30.00                         1           0          0
               40.10                         1           0          0
               53.00                         1           0          0
               62.00                         1           0          0
     August    2.00                          0           0          0
               7.00                          0           0          0
               14.00                         0           0          0
               19.00                         0           0          0
               25.50                         0           0          0
               28.10                         0           0          0
               40.00                         0           0          0
               52.00                         0           0          0
               61.10                         0           0          0
2017 April     2.20                          0           0          0
               5.20                          0           0          0
               10.10                         0           0          0
               20.20                         0           0          0
               30.10                         0           0          0
               40.20                         0           0          0
               52.10                         0           0          0
               60.40                         0           0          0

                               VALUE_2  UNITS_2  FRACTION_2  METHOD_2  \
YEAR MONTH     SAMPLE_DEPTH_M
1983 April     0.91                  0        0           0         0
               4.27                  0        0           0         0
               10.06                 0        0           0         0
               18.90                 0        0           0         0
               19.20                 0        0           0         0
               29.57                 0        0           0         0
               29.87                 0        0           0         0
               39.93                 0        0           0         0
               40.23                 0        0           0         0
               48.77                 0        0           0         0
               49.68                 0        0           0         0
               56.39                 0        0           0         0
               57.61                 0        0           0         0
     August    0.91                  0        0           0         0
               4.57                  0        0           0         0
               4.88                  0        0           0         0
               10.06                 0        0           0         0
               17.37                 0        0           0         0
               20.12                 0        0           0         0
               22.25                 0        0           0         0
               29.26                 0        0           0         0
               29.87                 0        0           0         0
               39.62                 0        0           0         0
               39.93                 0        0           0         0
               40.23                 0        0           0         0
               49.68                 0        0           0         0
               50.29                 0        0           0         0
               51.21                 0        0           0         0
               57.00                 0        0           0         0
               58.22                 0        0           0         0

In [4]:
df2=df[pd.to_numeric(df['SAMPLE_DEPTH_M'], errors='coerce').notnull()]
df2=df2[pd.to_numeric(df2['VALUE_1'], errors='coerce').notnull()]
df2['SAMPLE_DEPTH_M']=df2[['SAMPLE_DEPTH_M']].apply(pd.to_numeric)
df2['SAMPLE_DEPTH_M']=df2[['SAMPLE_DEPTH_M']]*-1
df2['VALUE_1']=df2[['VALUE_1']].apply(pd.to_numeric)

In [5]:
a = df2[df2['STATION_ID']=='ER15M']['SAMPLING_DATE'].unique()

In [6]:
b = df2[(df2['STATION_ID']=='ER15M') | (df2['STATION_ID']=='ER63') | (df2['STATION_ID']=='ER09') | (df2['STATION_ID']=='ER10') | (df2['STATION_ID']=='ER93B')]['SAMPLING_DATE'].unique()

In [7]:
np.sort(a)

array(['1983/04/26 02:10', '1983/04/27 08:15', '1983/05/09 23:18',
       '1983/08/07 21:55', '1983/08/09 04:17', '1983/08/23 01:35',
       '1983/10/21 15:00', '1983/10/21 22:30', '1984/04/18 22:00',
       '1984/04/20 04:35', '1984/05/01 23:32', '1984/08/06 19:04',
       '1984/08/08 01:20', '1984/08/20 14:45', '1984/12/05 13:12',
       '1984/12/05 23:35', '1985/04/26 03:54', '1985/04/27 11:55',
       '1985/08/08 04:40', '1985/08/13 01:05', '1985/11/22 21:10',
       '1985/11/23 19:50', '1986/04/19 08:20', '1986/04/26 10:55',
       '1986/08/07 23:20', '1986/08/14 10:40', '1987/04/03 21:25',
       '1987/04/06 02:55', '1987/04/19 16:55', '1987/08/01 13:45',
       '1987/08/16 11:35', '1988/04/09 21:20', '1988/04/16 02:05',
       '1988/08/18 13:45', '1989/08/14 16:30', '1989/08/20 01:55',
       '1990/04/12 01:13', '1990/04/18 15:05', '1990/08/10 04:25',
       '1990/08/16 01:34', '1991/04/07 01:40', '1991/04/14 10:42',
       '1991/08/09 13:00', '1991/08/15 07:00', '1992/04/03 20:00',
       '1992/04/09 11:15', '1996/04/16 08:38', '1996/04/21 19:10',
       '2016/04/06 13:13', '2016/08/12 14:56', '2017/04/07 04:29'],
      dtype=object)

In [12]:
np.sort(b)

array(['1983/04/26 02:10', '1983/04/26 05:10', '1983/04/27 06:20',
       '1983/04/27 08:15', '1983/05/09 23:18', '1983/05/10 01:10',
       '1983/08/07 21:55', '1983/08/08 01:45', '1983/08/09 04:17',
       '1983/08/09 06:30', '1983/08/23 01:35', '1983/08/23 03:45',
       '1983/10/21 15:00', '1983/10/21 17:50', '1983/10/21 20:25',
       '1983/10/21 22:30', '1984/04/18 22:00', '1984/04/19 00:25',
       '1984/04/20 02:18', '1984/04/20 04:35', '1984/05/01 21:30',
       '1984/05/01 23:32', '1984/08/06 19:04', '1984/08/06 21:03',
       '1984/08/07 22:04', '1984/08/08 01:20', '1984/08/20 14:45',
       '1984/08/20 16:38', '1984/12/05 13:12', '1984/12/05 15:12',
       '1984/12/05 21:45', '1984/12/05 23:35', '1985/04/26 02:16',
       '1985/04/26 03:54', '1985/04/26 05:50', '1985/04/26 07:25',
       '1985/04/27 08:00', '1985/04/27 09:25', '1985/04/27 11:55',
       '1985/04/27 13:05', '1985/08/08 03:00', '1985/08/08 04:40',
       '1985/08/08 07:35', '1985/08/08 09:30', '1985/08/12 21:25',
       '1985/08/12 23:10', '1985/08/13 01:05', '1985/08/13 02:45',
       '1985/11/22 19:30', '1985/11/22 21:10', '1985/11/22 22:58',
       '1985/11/23 00:28', '1985/11/23 15:15', '1985/11/23 17:58',
       '1985/11/23 19:50', '1985/11/23 21:09', '1986/04/19 06:40',
       '1986/04/19 08:20', '1986/04/19 10:54', '1986/04/19 12:36',
       '1986/04/26 07:30', '1986/04/26 08:50', '1986/04/26 10:55',
       '1986/04/26 12:25', '1986/08/07 21:35', '1986/08/07 23:20',
       '1986/08/08 01:34', '1986/08/08 04:00', '1986/08/14 06:35',
       '1986/08/14 08:30', '1986/08/14 10:40', '1986/08/14 12:20',
       '1987/04/03 21:25', '1987/04/03 23:51', '1987/04/04 01:34',
       '1987/04/04 03:27', '1987/04/05 21:45', '1987/04/05 23:30',
       '1987/04/06 01:10', '1987/04/06 02:55', '1987/04/19 15:25',
       '1987/04/19 16:55', '1987/04/19 19:24', '1987/04/19 20:50',
       '1987/08/01 11:56', '1987/08/01 13:45', '1987/08/01 16:10',
       '1987/08/01 17:17', '1987/08/16 07:15', '1987/08/16 09:10',
       '1987/08/16 11:35', '1987/08/16 13:15', '1988/04/09 19:38',
       '1988/04/09 21:20', '1988/04/09 23:45', '1988/04/10 02:25',
       '1988/04/15 22:25', '1988/04/16 00:02', '1988/04/16 02:05',
       '1988/04/16 03:55', '1988/08/12 16:30', '1988/08/12 21:30',
       '1988/08/12 23:30', '1988/08/18 08:59', '1988/08/18 11:25',
       '1988/08/18 13:45', '1988/08/18 15:35', '1989/08/14 14:30',
       '1989/08/14 16:30', '1989/08/14 19:00', '1989/08/14 21:15',
       '1989/08/19 21:47', '1989/08/19 23:45', '1989/08/20 01:55',
       '1989/08/20 03:51', '1990/04/12 00:10', '1990/04/12 01:13',
       '1990/04/12 04:19', '1990/04/12 06:25', '1990/04/17 15:50',
       '1990/04/17 18:00', '1990/04/18 13:15', '1990/04/18 15:05',
       '1990/08/10 02:10', '1990/08/10 04:25', '1990/08/10 07:30',
       '1990/08/10 09:45', '1990/08/15 20:50', '1990/08/15 23:14',
       '1990/08/16 01:34', '1990/08/16 03:55', '1991/04/06 23:00',
       '1991/04/07 01:40', '1991/04/07 04:50', '1991/04/07 07:30',
       '1991/04/14 06:58', '1991/04/14 09:00', '1991/04/14 10:42',
       '1991/04/14 13:10', '1991/08/09 10:30', '1991/08/09 13:00',
       '1991/08/09 15:45', '1991/08/09 18:30', '1991/08/15 03:00',
       '1991/08/15 04:45', '1991/08/15 07:00', '1991/08/15 10:15',
       '1992/04/03 17:35', '1992/04/03 20:00', '1992/04/03 23:15',
       '1992/04/04 01:15', '1992/04/09 07:00', '1992/04/09 08:30',
       '1992/04/09 11:15', '1992/04/09 14:00', '1996/04/16 07:20',
       '1996/04/16 08:38', '1996/04/16 10:40', '1996/04/16 12:40',
       '1996/04/21 15:35', '1996/04/21 17:05', '1996/04/21 19:10',
       '1996/04/21 21:10', '2016/04/06 13:13', '2016/04/06 14:49',
       '2016/04/06 16:18', '2016/04/06 17:36', '2016/08/12 12:01',
       '2016/08/12 14:56', '2016/08/12 18:55', '2016/08/12 20:58',
       '2017/04/07 04:29', '2017/04/08 08:51', '2017/04/08 10:30',
       '2017/04/08 11:58'], dtype=object)

In [11]:
df2[(df2['STATION_ID']=='ER09')  & ((df2['MONTH']=='April    ') | (df2['MONTH']=='August   '))].groupby(['YEAR', 'MONTH', 'SAMPLE_DEPTH_M']).mean()['VALUE_1']

YEAR  MONTH      SAMPLE_DEPTH_M
1983  April      -40.84            2.200000
                 -40.23            2.000000
                 -33.53            2.000000
                 -32.00            2.000000
                 -21.34            2.000000
                 -20.73            2.000000
                 -0.91             2.000000
      August     -41.15            2.666667
                 -34.14            4.000000
                 -33.53            0.500000
                 -30.48            0.500000
                 -19.51            0.000000
                 -17.68            0.500000
                 -10.67            0.000000
                 -10.06            0.000000
                 -7.62             1.000000
                 -0.91             0.000000
1984  April      -41.45            3.900000
                 -40.23            5.400000
                 -33.53            3.900000
                 -32.92            5.100000
                 -21.34            3.900000
                 -21.03            5.500000
                 -0.91             5.000000
      August     -41.45            3.900000
                 -41.15            1.300000
                 -36.27            1.900000
                 -33.22            0.200000
                 -32.92            3.500000
                 -30.48            1.600000
                                     ...
1991  August     -5.18             0.500000
                 -0.91             0.300000
1992  April      -46.33            7.300000
                 -45.42            6.200000
                 -37.80            7.100000
                 -36.58            6.400000
                 -22.86            6.200000
                 -17.68            7.300000
                 -0.91             7.050000
1996  April      -48.50            8.800000
                 -47.00            6.600000
                 -40.00            8.600000
                 -39.00            6.700000
                 -25.00            7.450000
                 -20.00            7.350000
                 -1.50             7.450000
                 -0.00             0.400000
2016  April      -48.20            5.200000
                 -39.70            5.200000
                 -24.60            4.115000
                 -2.00             4.160000
      August     -46.30            0.920000
                 -34.30            0.631000
                 -24.00            0.381000
                 -6.00             0.600000
                 -3.90            -0.094300
2017  April      -47.80            3.960000
                 -38.90            3.390000
                 -24.00            4.460000
                 -2.00             3.500000
Name: VALUE_1, Length: 188, dtype: float64

In [11]:
df2[(df2['STATION_ID']=='ER15M') & ((df2['MONTH']=='April    ') | (df2['MONTH']=='August   '))].groupby(['YEAR', 'MONTH', 'SAMPLE_DEPTH_M']).mean()['VALUE_1'].unstack(level=0).unstack(level=0)

YEAR                1983                1984                 1985            \
MONTH          April     August    April      August    April     August
SAMPLE_DEPTH_M
-61.700              NaN       NaN       NaN        NaN       NaN       NaN
-61.559              NaN       NaN       NaN        NaN       NaN       NaN
-61.000              NaN       NaN       NaN        NaN       NaN       NaN
-60.800              NaN       NaN       NaN        NaN       NaN       NaN
-60.700              NaN       NaN       NaN        NaN       NaN       NaN
-60.660              NaN       NaN       NaN        NaN       NaN       NaN
-60.350              NaN       NaN       NaN        NaN       NaN       NaN
-60.300              NaN       NaN       NaN        NaN       NaN       NaN
-60.095              NaN       NaN       NaN        NaN       NaN       NaN
-60.050              NaN       NaN       NaN        NaN       NaN       NaN
-60.000              NaN       NaN       NaN        NaN       NaN       NaN
-59.440              NaN       NaN       NaN        NaN      12.4       NaN
-59.130              NaN       NaN       NaN        NaN       NaN      11.6
-58.830              NaN       NaN       NaN        NaN       NaN       NaN
-58.220              NaN  8.250000       NaN  10.200000       NaN      10.4
-58.100              NaN       NaN       NaN        NaN       NaN       NaN
-58.000              NaN       NaN       NaN        NaN       NaN       NaN
-57.910              NaN       NaN      13.7        NaN      13.3       NaN
-57.610             11.7       NaN       NaN   8.500000       NaN       NaN
-57.600              NaN       NaN       NaN        NaN       NaN       NaN
-57.000              NaN  8.400000       NaN        NaN       NaN       NaN
-56.390             14.5       NaN      13.4        NaN       NaN       NaN
-52.200              NaN       NaN       NaN        NaN       NaN       NaN
-52.000              NaN       NaN       NaN        NaN       NaN       NaN
-51.820              NaN       NaN       NaN        NaN       NaN       NaN
-51.210              NaN  8.600000       NaN        NaN       NaN       NaN
-50.900              NaN       NaN       NaN  11.900000       NaN       NaN
-50.600              NaN       NaN       NaN        NaN      12.7       NaN
-50.290              NaN       NaN       NaN   8.500000       NaN       NaN
-49.990              NaN       NaN       NaN   9.400000       NaN       NaN
...                  ...       ...       ...        ...       ...       ...
-14.630              NaN       NaN       NaN        NaN       NaN       8.5
-14.020              NaN       NaN       NaN        NaN       NaN       NaN
-13.720              NaN       NaN       NaN        NaN       NaN       NaN
-12.500              NaN       NaN       NaN        NaN       NaN       NaN
-12.190              NaN       NaN       NaN        NaN       NaN       NaN
-11.580              NaN       NaN       NaN        NaN       NaN       NaN
-11.280              NaN       NaN       NaN        NaN       NaN       NaN
-10.970              NaN       NaN       NaN        NaN       NaN       NaN
-10.360              NaN       NaN       NaN        NaN       NaN       NaN
-10.060              NaN  8.466667      13.2   8.800000      13.0       NaN
-9.750               NaN       NaN      13.4        NaN      13.2       NaN
-9.450               NaN       NaN       NaN        NaN       NaN       9.8
-9.140               NaN       NaN       NaN        NaN       NaN       NaN
-7.920               NaN       NaN       NaN        NaN       NaN       NaN
-7.620               NaN       NaN       NaN        NaN       NaN       NaN
-7.320               NaN       NaN       NaN        NaN       NaN       NaN
-7.010               NaN       NaN       NaN  10.100000       NaN       NaN
-6.400               NaN       NaN       NaN        NaN       NaN       NaN
-5.180               NaN       NaN       NaN        NaN       NaN       NaN
-4.880               NaN  8.700000      13.7   9.166667      12.9       8.9
-4.570               NaN  8.650000       NaN        NaN       NaN       NaN
-4.270              12.6       NaN       NaN        NaN       NaN       NaN
-3.000               NaN       NaN       NaN        NaN       NaN       NaN
-2.600               NaN       NaN       NaN        NaN       NaN       NaN
-2.000               NaN       NaN       NaN        NaN       NaN       NaN
-1.500               NaN       NaN       NaN        NaN       NaN       NaN
-1.048               NaN       NaN       NaN        NaN       NaN       NaN
-1.000               NaN       NaN       NaN        NaN       NaN       NaN
-0.910               NaN  8.633333      13.5   9.200000      13.3       9.1
-0.893               NaN       NaN       NaN        NaN       NaN       NaN

YEAR                1986                 1987              ...         2003  \
MONTH          April     August     April     August       ...    April
SAMPLE_DEPTH_M                                             ...
-61.700              NaN       NaN        NaN       NaN    ...          NaN
-61.559              NaN       NaN        NaN       NaN    ...          NaN
-61.000              NaN       NaN        NaN       NaN    ...        13.96
-60.800              NaN       NaN        NaN       NaN    ...        14.02
-60.700              NaN       NaN        NaN       NaN    ...          NaN
-60.660              NaN       NaN  13.000000       NaN    ...          NaN
-60.350              NaN       NaN        NaN       NaN    ...          NaN
-60.300              NaN       NaN        NaN       NaN    ...          NaN
-60.095              NaN       NaN        NaN       NaN    ...          NaN
-60.050            11.70       NaN        NaN       NaN    ...          NaN
-60.000              NaN       NaN        NaN       NaN    ...          NaN
-59.440              NaN     10.65  13.200000       NaN    ...          NaN
-59.130             7.40       NaN        NaN      9.80    ...          NaN
-58.830              NaN       NaN  12.900000       NaN    ...          NaN
-58.220              NaN       NaN        NaN       NaN    ...          NaN
-58.100              NaN       NaN        NaN       NaN    ...          NaN
-58.000              NaN       NaN        NaN       NaN    ...          NaN
-57.910              NaN       NaN        NaN      9.80    ...          NaN
-57.610              NaN       NaN        NaN       NaN    ...          NaN
-57.600              NaN       NaN        NaN       NaN    ...          NaN
-57.000              NaN       NaN        NaN       NaN    ...          NaN
-56.390              NaN       NaN        NaN       NaN    ...          NaN
-52.200              NaN       NaN        NaN       NaN    ...          NaN
-52.000              NaN       NaN        NaN       NaN    ...          NaN
-51.820              NaN       NaN  13.300000       NaN    ...          NaN
-51.210              NaN       NaN        NaN       NaN    ...          NaN
-50.900             9.85       NaN        NaN       NaN    ...          NaN
-50.600              NaN       NaN  13.400000       NaN    ...          NaN
-50.290              NaN     10.80  12.800000       NaN    ...          NaN
-49.990              NaN       NaN        NaN       NaN    ...          NaN
...                  ...       ...        ...       ...    ...          ...
-14.630              NaN      8.20        NaN       NaN    ...          NaN
-14.020              NaN       NaN        NaN      8.30    ...          NaN
-13.720              NaN       NaN        NaN       NaN    ...          NaN
-12.500              NaN       NaN        NaN       NaN    ...          NaN
-12.190              NaN       NaN        NaN       NaN    ...          NaN
-11.580              NaN      9.60        NaN       NaN    ...          NaN
-11.280              NaN       NaN        NaN       NaN    ...          NaN
-10.970              NaN       NaN        NaN      7.40    ...          NaN
-10.360              NaN       NaN        NaN       NaN    ...          NaN
-10.060             7.40       NaN  13.200000       NaN    ...          NaN
-9.750               NaN       NaN  13.300000       NaN    ...          NaN
-9.450               NaN       NaN        NaN       NaN    ...          NaN
-9.140               NaN       NaN        NaN       NaN    ...          NaN
-7.920               NaN       NaN        NaN      8.40    ...          NaN
-7.620               NaN       NaN        NaN       NaN    ...          NaN
-7.320               NaN      8.40        NaN       NaN    ...          NaN
-7.010               NaN       NaN        NaN       NaN    ...          NaN
-6.400               NaN      9.10        NaN       NaN    ...          NaN
-5.180              6.80       NaN        NaN       NaN    ...          NaN
-4.880               NaN       NaN  13.266667      7.40    ...          NaN
-4.570               NaN       NaN        NaN       NaN    ...          NaN
-4.270               NaN       NaN        NaN       NaN    ...          NaN
-3.000               NaN       NaN        NaN       NaN    ...          NaN
-2.600               NaN       NaN        NaN       NaN    ...          NaN
-2.000               NaN       NaN        NaN       NaN    ...          NaN
-1.500               NaN       NaN        NaN       NaN    ...          NaN
-1.048               NaN       NaN        NaN       NaN    ...          NaN
-1.000               NaN       NaN        NaN       NaN    ...          NaN
-0.910             10.40      9.15  13.166667      8.35    ...          NaN
-0.893               NaN       NaN        NaN       NaN    ...          NaN

YEAR                          2004                2005                2007  \
MONTH          August    April     August    April     August    April
SAMPLE_DEPTH_M
-61.700              NaN       NaN       NaN       NaN       NaN       NaN
-61.559              NaN       NaN       NaN       NaN       NaN       NaN
-61.000              NaN       NaN       NaN       NaN       NaN       NaN
-60.800              NaN       NaN       NaN       NaN       NaN       NaN
-60.700              NaN       NaN       NaN       NaN       NaN       NaN
-60.660              NaN       NaN       NaN       NaN       NaN       NaN
-60.350              NaN       NaN       NaN       NaN       NaN       NaN
-60.300              NaN       NaN       NaN       NaN       NaN       NaN
-60.095              NaN       NaN       NaN       NaN       NaN       NaN
-60.050              NaN       NaN       NaN       NaN       NaN       NaN
-60.000              NaN       NaN       NaN       NaN       NaN       NaN
-59.440              NaN       NaN       NaN       NaN       NaN       NaN
-59.130              NaN       NaN       NaN       NaN       NaN       NaN
-58.830              NaN       NaN       NaN       NaN       NaN       NaN
-58.220              NaN       NaN       NaN       NaN       NaN       NaN
-58.100              NaN       NaN       NaN     13.68       NaN       NaN
-58.000              NaN       NaN       NaN       NaN       NaN       NaN
-57.910              NaN       NaN       NaN       NaN       NaN       NaN
-57.610              NaN       NaN       NaN       NaN       NaN       NaN
-57.600              NaN       NaN       NaN       NaN       NaN       NaN
-57.000              NaN       NaN       NaN       NaN       NaN       NaN
-56.390              NaN       NaN       NaN       NaN       NaN       NaN
-52.200              NaN       NaN       NaN       NaN       NaN       NaN
-52.000              NaN       NaN       NaN       NaN       NaN       NaN
-51.820              NaN       NaN       NaN       NaN       NaN       NaN
-51.210              NaN       NaN       NaN       NaN       NaN       NaN
-50.900              NaN       NaN       NaN       NaN       NaN       NaN
-50.600              NaN       NaN       NaN       NaN       NaN       NaN
-50.290              NaN       NaN       NaN       NaN       NaN       NaN
-49.990              NaN       NaN       NaN       NaN       NaN       NaN
...                  ...       ...       ...       ...       ...       ...
-14.630              NaN       NaN       NaN       NaN       NaN       NaN
-14.020              NaN       NaN       NaN       NaN       NaN       NaN
-13.720              NaN       NaN       NaN       NaN       NaN       NaN
-12.500              NaN       NaN       NaN       NaN       NaN       NaN
-12.190              NaN       NaN       NaN       NaN       NaN       NaN
-11.580              NaN       NaN       NaN       NaN       NaN       NaN
-11.280              NaN       NaN       NaN       NaN       NaN       NaN
-10.970              NaN       NaN       NaN       NaN       NaN       NaN
-10.360              NaN       NaN       NaN       NaN       NaN       NaN
-10.060              NaN       NaN       NaN       NaN       NaN       NaN
-9.750               NaN       NaN       NaN       NaN       NaN       NaN
-9.450               NaN       NaN       NaN       NaN       NaN       NaN
-9.140               NaN       NaN       NaN       NaN       NaN       NaN
-7.920               NaN       NaN       NaN       NaN       NaN       NaN
-7.620               NaN       NaN       NaN       NaN       NaN       NaN
-7.320               NaN       NaN       NaN       NaN       NaN       NaN
-7.010               NaN       NaN       NaN       NaN       NaN       NaN
-6.400               NaN       NaN       NaN       NaN       NaN       NaN
-5.180               NaN       NaN       NaN       NaN       NaN       NaN
-4.880               NaN       NaN       NaN       NaN       NaN       NaN
-4.570               NaN       NaN       NaN       NaN       NaN       NaN
-4.270               NaN       NaN       NaN       NaN       NaN       NaN
-3.000               NaN       NaN       NaN       NaN      8.36       NaN
-2.600               NaN       NaN       NaN       NaN       NaN       NaN
-2.000               NaN       NaN      8.46       NaN       NaN       NaN
-1.500               NaN       NaN       NaN       NaN       NaN       NaN
-1.048               NaN       NaN       NaN       NaN       NaN       NaN
-1.000              8.68       NaN       NaN       NaN       NaN       NaN
-0.910               NaN       NaN       NaN       NaN       NaN       NaN
-0.893               NaN       NaN       NaN       NaN       NaN       NaN

YEAR                          2012
MONTH          August    April     August
SAMPLE_DEPTH_M
-61.700              NaN     12.98       NaN
-61.559              NaN       NaN       NaN
-61.000              NaN       NaN       NaN
-60.800              NaN       NaN       NaN
-60.700              NaN       NaN       NaN
-60.660              NaN       NaN       NaN
-60.350              NaN       NaN       NaN
-60.300              NaN       NaN       NaN
-60.095              NaN       NaN       NaN
-60.050              NaN       NaN       NaN
-60.000              NaN       NaN       NaN
-59.440              NaN       NaN       NaN
-59.130              NaN       NaN       NaN
-58.830              NaN       NaN       NaN
-58.220              NaN       NaN       NaN
-58.100              NaN       NaN       NaN
-58.000              NaN       NaN       NaN
-57.910              NaN       NaN       NaN
-57.610              NaN       NaN       NaN
-57.600              NaN       NaN       NaN
-57.000              NaN       NaN       NaN
-56.390              NaN       NaN       NaN
-52.200              NaN       NaN      9.27
-52.000              9.6       NaN       NaN
-51.820              NaN       NaN       NaN
-51.210              NaN       NaN       NaN
-50.900              NaN       NaN       NaN
-50.600              NaN       NaN       NaN
-50.290              NaN       NaN       NaN
-49.990              NaN       NaN       NaN
...                  ...       ...       ...
-14.630              NaN       NaN       NaN
-14.020              NaN       NaN       NaN
-13.720              NaN       NaN       NaN
-12.500              NaN       NaN       NaN
-12.190              NaN       NaN       NaN
-11.580              NaN       NaN       NaN
-11.280              NaN       NaN       NaN
-10.970              NaN       NaN       NaN
-10.360              NaN       NaN       NaN
-10.060              NaN       NaN       NaN
-9.750               NaN       NaN       NaN
-9.450               NaN       NaN       NaN
-9.140               NaN       NaN       NaN
-7.920               NaN       NaN       NaN
-7.620               NaN       NaN       NaN
-7.320               NaN       NaN       NaN
-7.010               NaN       NaN       NaN
-6.400               NaN       NaN       NaN
-5.180               NaN       NaN       NaN
-4.880               NaN       NaN       NaN
-4.570               NaN       NaN       NaN
-4.270               NaN       NaN       NaN
-3.000               NaN       NaN       NaN
-2.600               NaN       NaN       NaN
-2.000               NaN       NaN       NaN
-1.500               NaN       NaN       NaN
-1.048               NaN       NaN       NaN
-1.000               NaN       NaN       NaN
-0.910               NaN       NaN       NaN
-0.893               NaN       NaN       NaN

[103 rows x 46 columns]

In [15]:
df2[((df2['STATION_ID']=='ER15M') | (df2['STATION_ID']=='ER63') | (df2['STATION_ID']=='ER09') | (df2['STATION_ID']=='ER10') | (df2['STATION_ID']=='ER93B')) & ((df2['MONTH']=='April    ') | (df2['MONTH']=='August   '))].groupby(['YEAR','MONTH', 'SAMPLE_DEPTH_M']).mean()['VALUE_1'].unstack(level=0).unstack(level=0).to_csv('po4_ee_glenda.csv')

In [13]:
df2.columns

Index(['Row', 'YEAR', 'MONTH', 'SEASON', 'LAKE', 'CRUISE_ID', 'VISIT_ID',
       'STATION_ID', 'STN_DEPTH_M', 'LATITUDE', 'LONGITUDE', 'SAMPLING_DATE',
       'TIME_ZONE', 'SAMPLE_DEPTH_M', 'DEPTH_CODE', 'MEDIUM', 'SAMPLE_TYPE',
       'QC_TYPE', 'SAMPLE_ID', 'ANL_CODE_1', 'ANALYTE_1', 'VALUE_1', 'UNITS_1',
       'FRACTION_1', 'METHOD_1', 'RESULT_REMARK_1', 'ANL_CODE_2', 'ANALYTE_2',
       'VALUE_2', 'UNITS_2', 'FRACTION_2', 'METHOD_2', 'RESULT_REMARK_2',
       'ANL_CODE_3', 'ANALYTE_3', 'VALUE_3', 'UNITS_3', 'FRACTION_3',
       'METHOD_3', 'RESULT_REMARK_3', 'ANL_CODE_4', 'ANALYTE_4', 'VALUE_4',
       'UNITS_4', 'FRACTION_4', 'METHOD_4', 'RESULT_REMARK_4', 'Unnamed: 47'],
      dtype='object')

In [18]:
df2[((df2['STATION_ID']=='ER15M') | (df2['STATION_ID']=='ER63') | (df2['STATION_ID']=='ER09') | (df2['STATION_ID']=='ER10') | (df2['STATION_ID']=='ER93B'))].groupby(['YEAR','MONTH', 'SAMPLE_DEPTH_M']).mean()['VALUE_1'].unstack(level=0).unstack(level=0).to_csv('test.csv')