In [1]:
import hydrofunctions as hf
import pandas as pd
import numpy as np
from zipfile import ZipFile
import os
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style("ticks")

In [2]:
import matplotlib.pyplot as plt
import numpy as np

from matplotlib import rc
import matplotlib.ticker as tkr
import matplotlib.dates as mdates
from datetime import datetime, timedelta
from matplotlib.colors import ListedColormap
import seaborn as sns
sns.set_style("whitegrid")
sns.set_style("ticks")
import scipy.io as sio
import cmocean

import sys
sys.path.append('../')


import warnings
warnings.filterwarnings('ignore')

%matplotlib inline


sns.set_style("whitegrid")
sns.set_style("ticks")

rc('text', usetex=False)
rc("savefig", dpi=90)
rc("figure", dpi=90)

plt.rcParams['figure.figsize'] = 6, 4

import pandas as pd

pd.options.display.max_columns = 999
pd.options.display.max_rows = 400

import h5py

from datetime import datetime
str(datetime.now())

'2019-04-04 12:07:37.175975'

In [3]:
import os
import os.path

canadian_rivers = pd.DataFrame({})

for dirpath, dirnames, filenames in os.walk("../Loadings Canada Chloride/Rivers/."):
    for filename in [f for f in filenames if f.endswith(".csv") and f.startswith("Flow")]:
        river = pd.read_csv(os.path.join(dirpath, filename))
        river[river.columns[0]] = pd.to_datetime(river[river.columns[0]], errors='coerce')
        river[filename[5:-8]] = river['Flow, CFS']
        river.set_index(river.columns[0], inplace=True)
        river = river[filename[5:-8]]
        canadian_rivers = canadian_rivers.join(river, how='outer')

In [5]:
(canadian_rivers.groupby(canadian_rivers.index.year).mean()[7:].T*3600*24*365*0.028*1e-9).round(6)

,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Niagara_R,167.985792,178.952152,181.362240,179.759520,177.533856,181.151056,186.345792,175.982112,187.937280,179.780188,177.365376,185.856768,194.556384,201.622745,215.810784
Grand_R,1.680921,1.984717,1.835248,2.501444,1.302143,3.011878,2.086793,1.430076,2.573839,1.387334,2.761975,2.681580,1.479228,1.830484,2.456974
Lynn_R,0.048541,0.059571,0.058669,0.070325,0.053777,0.064309,0.068164,0.047323,0.069951,0.047852,0.066864,0.068050,0.048281,0.043396,0.055941
St_Clair_R,150.805175,159.584524,157.753516,156.678289,151.505170,153.254780,164.578420,157.997876,148.683778,153.549402,151.501806,163.017486,171.416978,185.324049,184.738405
Canard_R,0.036103,0.062103,0.051334,0.063579,0.050791,0.082629,0.054496,0.037938,0.148307,0.020570,0.054635,0.053897,0.054409,0.049582,0.072691
Big_Otter_R,0.253351,0.285040,0.277027,0.361216,0.216879,0.389107,0.332661,0.179136,0.408850,0.204692,0.359890,0.339091,0.203984,0.208578,0.275622
Big_R,0.201351,0.228657,0.228906,0.286807,0.192817,0.273385,0.289892,0.177658,0.292574,0.181429,0.273359,0.267957,0.178119,0.189088,0.224650
Nanticoke_R,0.058192,0.060723,0.062626,0.086404,0.045050,0.081315,0.079346,0.040293,NaN,0.022551,0.070034,0.075106,0.043429,0.039743,0.067882
Turkey_R,0.008168,0.012089,0.009536,0.012121,0.009492,0.011692,0.009891,0.008454,0.018430,NaN,NaN,NaN,NaN,NaN,0.012208
Sydenham_R,0.571709,0.790084,0.971496,1.392751,0.715755,1.465372,0.897256,0.536131,1.594133,0.446281,1.019329,0.994670,0.588251,0.769476,1.054228
Kettle_R,0.086813,0.101200,0.105780,0.171150,0.075944,0.167440,0.123966,0.077044,0.237342,0.077659,0.176320,0.136142,0.082437,0.099476,0.110316
Thames_R,1.719370,2.074855,2.116906,2.816766,1.494887,3.149357,2.856905,1.550434,3.882693,1.474388,3.281484,2.861427,1.637637,1.966414,2.771791
Ruscom_R,0.027683,0.032640,0.030410,0.040544,0.029178,0.048271,0.028377,0.017615,0.076077,0.012771,0.034197,0.033400,0.027969,0.029656,0.035067
Welland_R,6.301489,6.353039,6.713772,5.544089,5.707195,6.644756,6.136840,5.342164,4.747920,6.434981,5.489268,6.522647,7.099142,6.560531,4.376903

In [6]:
import os
import os.path

us_rivers = pd.DataFrame({})

for dirpath, dirnames, filenames in os.walk("../Loadings US Chloride/Rivers/."):
    for filename in [f for f in filenames if f.endswith(".csv") and f.startswith("Flow")]:
        river = pd.read_csv(os.path.join(dirpath, filename))
        river[river.columns[0]] = pd.to_datetime(river[river.columns[0]], errors='coerce')
        river[filename[5:-8]] = river['Flow, CFS']
        river.set_index(river.columns[0], inplace=True)
        river = river[filename[5:-8]]
        us_rivers = us_rivers.join(river, how='outer')

In [7]:
(us_rivers.groupby(us_rivers.index.year).mean()[7:-1].T*3600*24*365*0.028*1e-9).round(6)

Date,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Rouge_R,0.105399,0.133022,0.125940,0.167635,0.144864,0.163919,0.162742,0.105065,0.218077,0.095993,0.136587,0.158506,0.121328,0.121599,0.151679
Portage_R,0.507951,0.364286,0.519741,0.557561,0.601638,0.656907,0.360759,0.304437,1.197068,0.297217,0.580239,0.369087,0.536318,0.326414,0.563816
Buffalo_R,0.600852,0.725600,0.628806,0.646013,0.495155,0.443963,0.434833,0.300294,0.482248,0.293520,0.584535,0.582770,0.493425,0.402917,0.724518
Raisin_R,0.525263,0.623246,0.576256,1.007795,0.835997,1.066992,0.919170,0.688202,1.279130,0.499308,0.624654,0.640728,0.647980,0.589573,0.820935
Grand_OH_R,1.132470,1.043408,1.106746,1.357348,0.995479,1.157761,0.672271,0.710863,1.570946,0.760284,1.052949,0.931754,0.810097,0.714572,0.988644
Cattaraugus_R,0.771105,0.839285,0.674643,0.842922,0.713344,0.778275,0.791383,0.622869,0.864438,0.571473,0.746672,0.626679,0.628225,0.540752,0.905253
Conneaut_R,0.307386,0.361116,0.345220,0.335045,0.277939,0.331468,0.218455,0.216607,0.384156,0.235095,0.319521,0.272061,0.194743,0.201158,0.279225
Chagrin_R,0.396776,0.430700,0.600785,0.512747,0.430058,0.485945,0.285322,0.286170,0.660783,0.354276,0.379783,0.405726,0.331914,0.280643,0.406134
Belle_R,0.060910,0.115206,0.089759,0.135395,0.073791,0.121454,0.165121,0.062987,0.149207,0.057373,0.088630,0.089625,0.066026,0.090344,0.098895
Cuyahoga_R,1.505952,1.537056,1.335710,1.358693,1.288761,1.432659,0.707574,0.875245,1.896036,1.112489,1.166952,1.266001,1.108606,0.993121,1.405502
Black_R_MI,0.046535,0.115273,0.094655,0.139848,0.075261,0.112614,0.136483,0.062567,0.143580,0.049703,0.109671,0.079539,0.068065,0.096145,0.086359
Sandusky_R,1.409109,1.219004,1.384506,1.353784,1.668295,1.695519,0.804515,0.924102,2.630459,0.883477,1.654487,1.019920,1.164128,0.756779,1.365667
Huron_OH_R,0.371413,0.379922,0.483807,0.362380,0.477827,0.555941,0.298856,0.215222,0.697536,0.291996,0.428674,0.338710,0.314246,0.245411,0.370753
Clinton_R,0.407026,0.598257,0.508285,0.703847,0.520435,0.719783,0.985604,0.460098,0.916749,0.403641,0.610899,0.656329,0.492798,0.524148,0.678067
Huron_MI_R,0.258005,0.420440,0.395018,0.539714,0.500497,0.600913,0.705705,0.444177,0.742208,0.401251,0.462007,0.508303,0.374652,0.372815,0.522597
Rocky_R,0.368801,0.432587,0.390633,0.366671,0.367103,0.460955,0.265718,0.194925,0.645459,0.337268,0.346402,0.374248,0.323729,0.229891,0.347093
Black_OH_R,0.402877,0.508219,0.480027,0.417877,0.449258,0.579385,0.284124,0.240726,0.760231,0.353611,0.441897,0.419226,0.304073,0.248951,0.356152
Detroit_R,153.297791,163.627039,161.567991,160.615007,154.811519,159.053453,173.038664,165.038375,158.449758,156.587061,155.491853,168.818328,179.705571,192.363123,188.854485
Maumee_R,6.830974,5.096148,5.684549,6.201571,7.005231,6.759964,5.081776,4.156391,9.426456,2.861887,5.486741,5.334266,6.647710,3.955263,7.095095
Vermilion_R,0.274622,0.346438,0.369365,0.287300,0.388354,0.434132,0.190007,0.171039,0.491987,0.221727,0.270376,0.253762,0.204161,0.176533,0.260818

In [8]:
import pandas as pd
WSC_STATIONS = pd.read_pickle('../Loadings Canada 2/data/WSC_STATIONS')
WSC_STATIONS = WSC_STATIONS[WSC_STATIONS.Flow == True]

In [88]:
site = '02GE006'

df = WSC_STATIONS[WSC_STATIONS.STATION_NUMBER==site][[
    'STATION_NAME',
    'STATION_NUMBER',
    'LATITUDE',
    'LONGITUDE',
    'DRAINAGE_AREA_GROSS'
]]
df['STATION_NAME'] = df['STATION_NAME'].apply(lambda x: x.title())
df

In [3]:
from zipfile import ZipFile

import pandas as pd
import pyperclip

stations = pd.read_csv('../../measurements/USGS stream data/OHIO station info.csv')
stations_1 = pd.read_csv(ZipFile('../../measurements/USGS stream data/MICHIGAN stations.zip').open(name='station.csv'))
stations_2 = pd.read_csv(ZipFile('../../measurements/USGS stream data/NEW YORK stations.zip').open(name='station.csv'))




stations = stations.append(stations_1.append(stations_2))

station = 'dv04165710'
res = stations[stations.MonitoringLocationIdentifier == 'USGS-'+station[2:]][
    ['MonitoringLocationIdentifier',
        'MonitoringLocationName',
     'LatitudeMeasure',
     'LongitudeMeasure',
     'DrainageAreaMeasure/MeasureValue',
    ]
]
res['MonitoringLocationName'] = res['MonitoringLocationName'].apply(lambda x: x.title())
res = res.values[0]
print('{} {} {} {} {}'.format(*[i for i in res]))
pyperclip.copy('{}\t{}\t{}\t{}\t{}'.format(*[i for i in res]))

# Correlations

          index  Detroit_R
0    1996-01-01        NaN
1    1996-01-02        NaN
2    1996-01-03        NaN
3    1996-01-04        NaN
4    1996-01-05        NaN
5    1996-01-06        NaN
6    1996-01-07        NaN
7    1996-01-08        NaN
8    1996-01-09        NaN
9    1996-01-10        NaN
10   1996-01-11        NaN
11   1996-01-12        NaN
12   1996-01-13        NaN
13   1996-01-14        NaN
14   1996-01-15        NaN
15   1996-01-16        NaN
16   1996-01-17        NaN
17   1996-01-18        NaN
18   1996-01-19        NaN
19   1996-01-20        NaN
20   1996-01-21        NaN
21   1996-01-22        NaN
22   1996-01-23        NaN
23   1996-01-24        NaN
24   1996-01-25        NaN
25   1996-01-26        NaN
26   1996-01-27        NaN
27   1996-01-28        NaN
28   1996-01-29        NaN
29   1996-01-30        NaN
30   1996-01-31        NaN
31   1996-02-01        NaN
32   1996-02-02        NaN
33   1996-02-03        NaN
34   1996-02-04        NaN
35   1996-02-05        NaN
36   1996-02-06        NaN
37   1996-02-07        NaN
38   1996-02-08        NaN
39   1996-02-09        NaN
40   1996-02-10        NaN
41   1996-02-11        NaN
42   1996-02-12        NaN
43   1996-02-13        NaN
44   1996-02-14        NaN
45   1996-02-15        NaN
46   1996-02-16        NaN
47   1996-02-17        NaN
48   1996-02-18        NaN
49   1996-02-19        NaN
50   1996-02-20        NaN
51   1996-02-21        NaN
52   1996-02-22        NaN
53   1996-02-23        NaN
54   1996-02-24        NaN
55   1996-02-25        NaN
56   1996-02-26        NaN
57   1996-02-27        NaN
58   1996-02-28        NaN
59   1996-02-29        NaN
60   1996-03-01        NaN
61   1996-03-02        NaN
62   1996-03-03        NaN
63   1996-03-04        NaN
64   1996-03-05        NaN
65   1996-03-06        NaN
66   1996-03-07        NaN
67   1996-03-08        NaN
68   1996-03-09        NaN
69   1996-03-10        NaN
70   1996-03-11        NaN
71   1996-03-12        NaN
72   1996-03-13        NaN
73   1996-03-14        NaN
74   1996-03-15        NaN
75   1996-03-16        NaN
76   1996-03-17        NaN
77   1996-03-18        NaN
78   1996-03-19        NaN
79   1996-03-20        NaN
80   1996-03-21        NaN
81   1996-03-22        NaN
82   1996-03-23        NaN
83   1996-03-24        NaN
84   1996-03-25        NaN
85   1996-03-26        NaN
86   1996-03-27        NaN
87   1996-03-28        NaN
88   1996-03-29        NaN
89   1996-03-30        NaN
90   1996-03-31        NaN
91   1996-04-01        NaN
92   1996-04-02        NaN
93   1996-04-03        NaN
94   1996-04-04        NaN
95   1996-04-05        NaN
96   1996-04-06        NaN
97   1996-04-07        NaN
98   1996-04-08        NaN
99   1996-04-09        NaN
100  1996-04-10        NaN
101  1996-04-11        NaN
102  1996-04-12        NaN
103  1996-04-13        NaN
104  1996-04-14        NaN
105  1996-04-15        NaN
106  1996-04-16        NaN
107  1996-04-17        NaN
108  1996-04-18        NaN
109  1996-04-19        NaN
110  1996-04-20        NaN
111  1996-04-21        NaN
112  1996-04-22        NaN
113  1996-04-23        NaN
114  1996-04-24        NaN
115  1996-04-25        NaN
116  1996-04-26        NaN
117  1996-04-27        NaN
118  1996-04-28        NaN
119  1996-04-29        NaN
120  1996-04-30        NaN
121  1996-05-01        NaN
122  1996-05-02        NaN
123  1996-05-03        NaN
124  1996-05-04        NaN
125  1996-05-05        NaN
126  1996-05-06        NaN
127  1996-05-07        NaN
128  1996-05-08        NaN
129  1996-05-09        NaN
130  1996-05-10        NaN
131  1996-05-11        NaN
132  1996-05-12        NaN
133  1996-05-13        NaN
134  1996-05-14        NaN
135  1996-05-15        NaN
136  1996-05-16        NaN
137  1996-05-17        NaN
138  1996-05-18        NaN
139  1996-05-19        NaN
140  1996-05-20        NaN
141  1996-05-21        NaN
142  1996-05-22        NaN
143  1996-05-23        NaN
144  1996-05-24        NaN
145  1996-05-25        NaN
146  1996-05-26        NaN
147  1996-05-27        NaN
148  1996-05-28        NaN
149  1996-05-29        NaN
150  1996-05-30        NaN
151  1996-05-31        NaN
152  1996-06-01        NaN
153  1996-06-02        NaN
154  1996-06-03        NaN
155  1996-06-04        NaN
156  1996-06-05        NaN
157  1996-06-06        NaN
158  1996-06-07        NaN
159  1996-06-08        NaN
160  1996-06-09        NaN
161  1996-06-10        NaN
162  1996-06-11        NaN
163  1996-06-12        NaN
164  1996-06-13        NaN
165  1996-06-14        NaN
166  1996-06-15        NaN
167  1996-06-16        NaN
168  1996-06-17        NaN
169  1996-06-18        NaN
170  1996-06-19        NaN
171  1996-06-20        NaN
172  1996-06-21        NaN
173  1996-06-22        NaN
174  1996-06-23        NaN
175  1996-06-24        NaN
176  1996-06-25        NaN
177  1996-06-26        NaN
178  1996-06-27        NaN
179  1996-06-28        NaN
180  1996-06-29        NaN
181  1996-06-30        NaN
182  1996-07-01        NaN
183  1996-07-02        NaN
184  1996-07-03        NaN
185  1996-07-04        NaN
186  1996-07-05        NaN
187  1996-07-06        NaN
188  1996-07-07        NaN
189  1996-07-08        NaN
190  1996-07-09        NaN
191  1996-07-10        NaN
192  1996-07-11        NaN
193  1996-07-12        NaN
194  1996-07-13        NaN
195  1996-07-14        NaN
196  1996-07-15        NaN
197  1996-07-16        NaN
198  1996-07-17        NaN
199  1996-07-18        NaN
...         ...        ...
8141 2018-04-16        NaN
8142 2018-04-17        NaN
8143 2018-04-18        NaN
8144 2018-04-19        NaN
8145 2018-04-20        NaN
8146 2018-04-21        NaN
8147 2018-04-22        NaN
8148 2018-04-23        NaN
8149 2018-04-24        NaN
8150 2018-04-25        NaN
8151 2018-04-26        NaN
8152 2018-04-27        NaN
8153 2018-04-28        NaN
8154 2018-04-29        NaN
8155 2018-04-30        NaN
8156 2018-05-01        NaN
8157 2018-05-02        NaN
8158 2018-05-03        NaN
8159 2018-05-04        NaN
8160 2018-05-05        NaN
8161 2018-05-06        NaN
8162 2018-05-07        NaN
8163 2018-05-08        NaN
8164 2018-05-09        NaN
8165 2018-05-10        NaN
8166 2018-05-11        NaN
8167 2018-05-12        NaN
8168 2018-05-13        NaN
8169 2018-05-14        NaN
8170 2018-05-15        NaN
8171 2018-05-16        NaN
8172 2018-05-17        NaN
8173 2018-05-18        NaN
8174 2018-05-19        NaN
8175 2018-05-20        NaN
8176 2018-05-21        NaN
8177 2018-05-22        NaN
8178 2018-05-23        NaN
8179 2018-05-24        NaN
8180 2018-05-25        NaN
8181 2018-05-26        NaN
8182 2018-05-27        NaN
8183 2018-05-28        NaN
8184 2018-05-29        NaN
8185 2018-05-30        NaN
8186 2018-05-31        NaN
8187 2018-06-01        NaN
8188 2018-06-02        NaN
8189 2018-06-03        NaN
8190 2018-06-04        NaN
8191 2018-06-05        NaN
8192 2018-06-06        NaN
8193 2018-06-07        NaN
8194 2018-06-08        NaN
8195 2018-06-09        NaN
8196 2018-06-10        NaN
8197 2018-06-11        NaN
8198 2018-06-12        NaN
8199 2018-06-13        NaN
8200 2018-06-14        NaN
8201 2018-06-15        NaN
8202 2018-06-16        NaN
8203 2018-06-17        NaN
8204 2018-06-18        NaN
8205 2018-06-19        NaN
8206 2018-06-20        NaN
8207 2018-06-21        NaN
8208 2018-06-22        NaN
8209 2018-06-23        NaN
8210 2018-06-24        NaN
8211 2018-06-25        NaN
8212 2018-06-26        NaN
8213 2018-06-27        NaN
8214 2018-06-28        NaN
8215 2018-06-29        NaN
8216 2018-06-30        NaN
8217 2018-07-01        NaN
8218 2018-07-02        NaN
8219 2018-07-03        NaN
8220 2018-07-04        NaN
8221 2018-07-05        NaN
8222 2018-07-06        NaN
8223 2018-07-07        NaN
8224 2018-07-08        NaN
8225 2018-07-09        NaN
8226 2018-07-10        NaN
8227 2018-07-11        NaN
8228 2018-07-12        NaN
8229 2018-07-13        NaN
8230 2018-07-14        NaN
8231 2018-07-15        NaN
8232 2018-07-16        NaN
8233 2018-07-17        NaN
8234 2018-07-18        NaN
8235 2018-07-19        NaN
8236 2018-07-20        NaN
8237 2018-07-21        NaN
8238 2018-07-22        NaN
8239 2018-07-23        NaN
8240 2018-07-24        NaN
8241 2018-07-25        NaN
8242 2018-07-26        NaN
8243 2018-07-27        NaN
8244 2018-07-28        NaN
8245 2018-07-29        NaN
8246 2018-07-30        NaN
8247 2018-07-31        NaN
8248 2018-08-01        NaN
8249 2018-08-02        NaN
8250 2018-08-03        NaN
8251 2018-08-04        NaN
8252 2018-08-05        NaN
8253 2018-08-06        NaN
8254 2018-08-07        NaN
8255 2018-08-08        NaN
8256 2018-08-09        NaN
8257 2018-08-10        NaN
8258 2018-08-11        NaN
8259 2018-08-12        NaN
8260 2018-08-13        NaN
8261 2018-08-14        NaN
8262 2018-08-15        NaN
8263 2018-08-16        NaN
8264 2018-08-17        NaN
8265 2018-08-18        NaN
8266 2018-08-19        NaN
8267 2018-08-20        NaN
8268 2018-08-21        NaN
8269 2018-08-22        NaN
8270 2018-08-23        NaN
8271 2018-08-24        NaN
8272 2018-08-25        NaN
8273 2018-08-26        NaN
8274 2018-08-27        NaN
8275 2018-08-28        NaN
8276 2018-08-29        NaN
8277 2018-08-30        NaN
8278 2018-08-31        NaN
8279 2018-09-01        NaN
8280 2018-09-02        NaN
8281 2018-09-03        NaN
8282 2018-09-04        NaN
8283 2018-09-05        NaN
8284 2018-09-06        NaN
8285 2018-09-07        NaN
8286 2018-09-08        NaN
8287 2018-09-09        NaN
8288 2018-09-10        NaN
8289 2018-09-11        NaN
8290 2018-09-12        NaN
8291 2018-09-13        NaN
8292 2018-09-14        NaN
8293 2018-09-15        NaN
8294 2018-09-16        NaN
8295 2018-09-17        NaN
8296 2018-09-18        NaN
8297 2018-09-19        NaN
8298 2018-09-20        NaN
8299 2018-09-21        NaN
8300 2018-09-22        NaN
8301 2018-09-23        NaN
8302 2018-09-24        NaN
8303 2018-09-25        NaN
8304 2018-09-26        NaN
8305 2018-09-27        NaN
8306 2018-09-28        NaN
8307 2018-09-29        NaN
8308 2018-09-30        NaN
8309 2018-10-01        NaN
8310 2018-10-02        NaN
8311 2018-10-03        NaN
8312 2018-10-04        NaN
8313 2018-10-05        NaN
8314 2018-10-06        NaN
8315 2018-10-07        NaN
8316 2018-10-08        NaN
8317 2018-10-09        NaN
8318 2018-10-10        NaN
8319 2018-10-11        NaN
8320 2018-10-12        NaN
8321 2018-10-13        NaN
8322 2018-10-14        NaN
8323 2018-10-15        NaN
8324 2018-10-16        NaN
8325 2018-10-17        NaN
8326 2018-10-18        NaN
8327 2018-10-19        NaN
8328 2018-10-20        NaN
8329 2018-10-21        NaN
8330 2018-10-22        NaN
8331 2018-10-23        NaN
8332 2018-10-24        NaN
8333 2018-10-25        NaN
8334 2018-10-26        NaN
8335 2018-10-27        NaN
8336 2018-10-28        NaN
8337 2018-10-29        NaN
8338 2018-10-30        NaN
8339 2018-10-31        NaN
8340 2018-11-01        NaN

[8341 rows x 2 columns]

In [21]:
canadian_rivers['St_Clair_R'].reset_index()

           index     St_Clair_R
0     1996-01-02            NaN
1     1996-01-02            NaN
2     1996-01-03            NaN
3     1996-01-03            NaN
4     1996-01-04            NaN
5     1996-01-04            NaN
6     1996-01-05            NaN
7     1996-01-05            NaN
8     1996-01-06            NaN
9     1996-01-06            NaN
10    1996-01-07            NaN
11    1996-01-07            NaN
12    1996-01-08            NaN
13    1996-01-08            NaN
14    1996-01-09            NaN
15    1996-01-09            NaN
16    1996-01-10            NaN
17    1996-01-10            NaN
18    1996-01-11            NaN
19    1996-01-11            NaN
20    1996-01-12            NaN
21    1996-01-12            NaN
22    1996-01-13            NaN
23    1996-01-13            NaN
24    1996-01-14            NaN
25    1996-01-14            NaN
26    1996-01-15            NaN
27    1996-01-15            NaN
28    1996-01-16            NaN
29    1996-01-16            NaN
30    1996-01-17            NaN
31    1996-01-17            NaN
32    1996-01-18            NaN
33    1996-01-18            NaN
34    1996-01-19            NaN
35    1996-01-19            NaN
36    1996-01-20            NaN
37    1996-01-20            NaN
38    1996-01-21            NaN
39    1996-01-21            NaN
40    1996-01-22            NaN
41    1996-01-22            NaN
42    1996-01-23            NaN
43    1996-01-23            NaN
44    1996-01-24            NaN
45    1996-01-24            NaN
46    1996-01-25            NaN
47    1996-01-25            NaN
48    1996-01-26            NaN
49    1996-01-26            NaN
50    1996-01-27            NaN
51    1996-01-27            NaN
52    1996-01-28            NaN
53    1996-01-28            NaN
54    1996-01-29            NaN
55    1996-01-29            NaN
56    1996-01-30            NaN
57    1996-01-30            NaN
58    1996-01-31            NaN
59    1996-01-31            NaN
60    1996-02-01            NaN
61    1996-02-01            NaN
62    1996-02-02            NaN
63    1996-02-02            NaN
64    1996-02-03            NaN
65    1996-02-03            NaN
66    1996-02-04            NaN
67    1996-02-04            NaN
68    1996-02-05            NaN
69    1996-02-05            NaN
70    1996-02-06            NaN
71    1996-02-06            NaN
72    1996-02-07            NaN
73    1996-02-07            NaN
74    1996-02-08            NaN
75    1996-02-08            NaN
76    1996-02-09            NaN
77    1996-02-09            NaN
78    1996-02-10            NaN
79    1996-02-10            NaN
80    1996-02-11            NaN
81    1996-02-11            NaN
82    1996-02-12            NaN
83    1996-02-12            NaN
84    1996-02-13            NaN
85    1996-02-13            NaN
86    1996-02-14            NaN
87    1996-02-14            NaN
88    1996-02-15            NaN
89    1996-02-15            NaN
90    1996-02-16            NaN
91    1996-02-16            NaN
92    1996-02-17            NaN
93    1996-02-17            NaN
94    1996-02-18            NaN
95    1996-02-18            NaN
96    1996-02-19            NaN
97    1996-02-19            NaN
98    1996-02-20            NaN
99    1996-02-20            NaN
100   1996-02-21            NaN
101   1996-02-21            NaN
102   1996-02-22            NaN
103   1996-02-22            NaN
104   1996-02-23            NaN
105   1996-02-23            NaN
106   1996-02-24            NaN
107   1996-02-24            NaN
108   1996-02-25            NaN
109   1996-02-25            NaN
110   1996-02-26            NaN
111   1996-02-26            NaN
112   1996-02-27            NaN
113   1996-02-27            NaN
114   1996-02-28            NaN
115   1996-02-28            NaN
116   1996-02-29            NaN
117   1996-02-29            NaN
118   1996-03-01            NaN
119   1996-03-01            NaN
120   1996-03-02            NaN
121   1996-03-02            NaN
122   1996-03-03            NaN
123   1996-03-03            NaN
124   1996-03-04            NaN
125   1996-03-04            NaN
126   1996-03-05            NaN
127   1996-03-05            NaN
128   1996-03-06            NaN
129   1996-03-06            NaN
130   1996-03-07            NaN
131   1996-03-07            NaN
132   1996-03-08            NaN
133   1996-03-08            NaN
134   1996-03-09            NaN
135   1996-03-09            NaN
136   1996-03-10            NaN
137   1996-03-10            NaN
138   1996-03-11            NaN
139   1996-03-11            NaN
140   1996-03-12            NaN
141   1996-03-12            NaN
142   1996-03-13            NaN
143   1996-03-13            NaN
144   1996-03-14            NaN
145   1996-03-14            NaN
146   1996-03-15            NaN
147   1996-03-15            NaN
148   1996-03-16            NaN
149   1996-03-16            NaN
150   1996-03-17            NaN
151   1996-03-17            NaN
152   1996-03-18            NaN
153   1996-03-18            NaN
154   1996-03-19            NaN
155   1996-03-19            NaN
156   1996-03-20            NaN
157   1996-03-20            NaN
158   1996-03-21            NaN
159   1996-03-21            NaN
160   1996-03-22            NaN
161   1996-03-22            NaN
162   1996-03-23            NaN
163   1996-03-23            NaN
164   1996-03-24            NaN
165   1996-03-24            NaN
166   1996-03-25            NaN
167   1996-03-25            NaN
168   1996-03-26            NaN
169   1996-03-26            NaN
170   1996-03-27            NaN
171   1996-03-27            NaN
172   1996-03-28            NaN
173   1996-03-28            NaN
174   1996-03-29            NaN
175   1996-03-29            NaN
176   1996-03-30            NaN
177   1996-03-30            NaN
178   1996-03-31            NaN
179   1996-03-31            NaN
180   1996-04-01            NaN
181   1996-04-01            NaN
182   1996-04-02            NaN
183   1996-04-02            NaN
184   1996-04-03            NaN
185   1996-04-03            NaN
186   1996-04-04            NaN
187   1996-04-04            NaN
188   1996-04-05            NaN
189   1996-04-05            NaN
190   1996-04-06            NaN
191   1996-04-06            NaN
192   1996-04-07            NaN
193   1996-04-07            NaN
194   1996-04-08            NaN
195   1996-04-08            NaN
196   1996-04-09            NaN
197   1996-04-09            NaN
198   1996-04-10            NaN
199   1996-04-10            NaN
...          ...            ...
15870 2017-09-23  210353.371429
15871 2017-09-23  210353.371429
15872 2017-09-24  210353.371429
15873 2017-09-24  210353.371429
15874 2017-09-25  209342.057143
15875 2017-09-25  209342.057143
15876 2017-09-26  208330.742857
15877 2017-09-26  208330.742857
15878 2017-09-27  216421.257143
15879 2017-09-27  216421.257143
15880 2017-09-28  226534.400000
15881 2017-09-28  226534.400000
15882 2017-09-29  229568.342857
15883 2017-09-29  229568.342857
15884 2017-09-30  229568.342857
15885 2017-09-30  229568.342857
15886 2017-10-01            NaN
15887 2017-10-01            NaN
15888 2017-10-02            NaN
15889 2017-10-02            NaN
15890 2017-10-03            NaN
15891 2017-10-03            NaN
15892 2017-10-04            NaN
15893 2017-10-04            NaN
15894 2017-10-05            NaN
15895 2017-10-05            NaN
15896 2017-10-06            NaN
15897 2017-10-06            NaN
15898 2017-10-07            NaN
15899 2017-10-07            NaN
15900 2017-10-08            NaN
15901 2017-10-08            NaN
15902 2017-10-09            NaN
15903 2017-10-09            NaN
15904 2017-10-10            NaN
15905 2017-10-10            NaN
15906 2017-10-11            NaN
15907 2017-10-11            NaN
15908 2017-10-12            NaN
15909 2017-10-12            NaN
15910 2017-10-13            NaN
15911 2017-10-13            NaN
15912 2017-10-14            NaN
15913 2017-10-14            NaN
15914 2017-10-15            NaN
15915 2017-10-15            NaN
15916 2017-10-16            NaN
15917 2017-10-16            NaN
15918 2017-10-17            NaN
15919 2017-10-17            NaN
15920 2017-10-18            NaN
15921 2017-10-18            NaN
15922 2017-10-19            NaN
15923 2017-10-19            NaN
15924 2017-10-20            NaN
15925 2017-10-20            NaN
15926 2017-10-21            NaN
15927 2017-10-21            NaN
15928 2017-10-22            NaN
15929 2017-10-22            NaN
15930 2017-10-23            NaN
15931 2017-10-23            NaN
15932 2017-10-24            NaN
15933 2017-10-24            NaN
15934 2017-10-25            NaN
15935 2017-10-25            NaN
15936 2017-10-26            NaN
15937 2017-10-26            NaN
15938 2017-10-27            NaN
15939 2017-10-27            NaN
15940 2017-10-28            NaN
15941 2017-10-28            NaN
15942 2017-10-29            NaN
15943 2017-10-29            NaN
15944 2017-10-30            NaN
15945 2017-10-30            NaN
15946 2017-10-31            NaN
15947 2017-10-31            NaN
15948 2017-11-01            NaN
15949 2017-11-01            NaN
15950 2017-11-02            NaN
15951 2017-11-02            NaN
15952 2017-11-03            NaN
15953 2017-11-03            NaN
15954 2017-11-04            NaN
15955 2017-11-04            NaN
15956 2017-11-05            NaN
15957 2017-11-05            NaN
15958 2017-11-06            NaN
15959 2017-11-06            NaN
15960 2017-11-07            NaN
15961 2017-11-07            NaN
15962 2017-11-08            NaN
15963 2017-11-08            NaN
15964 2017-11-09            NaN
15965 2017-11-09            NaN
15966 2017-11-10            NaN
15967 2017-11-10            NaN
15968 2017-11-11            NaN
15969 2017-11-11            NaN
15970 2017-11-12            NaN
15971 2017-11-12            NaN
15972 2017-11-13            NaN
15973 2017-11-13            NaN
15974 2017-11-14            NaN
15975 2017-11-14            NaN
15976 2017-11-15            NaN
15977 2017-11-15            NaN
15978 2017-11-16            NaN
15979 2017-11-16            NaN
15980 2017-11-17            NaN
15981 2017-11-17            NaN
15982 2017-11-18            NaN
15983 2017-11-18            NaN
15984 2017-11-19            NaN
15985 2017-11-19            NaN
15986 2017-11-20            NaN
15987 2017-11-20            NaN
15988 2017-11-21            NaN
15989 2017-11-21            NaN
15990 2017-11-22            NaN
15991 2017-11-22            NaN
15992 2017-11-23            NaN
15993 2017-11-23            NaN
15994 2017-11-24            NaN
15995 2017-11-24            NaN
15996 2017-11-25            NaN
15997 2017-11-25            NaN
15998 2017-11-26            NaN
15999 2017-11-26            NaN
16000 2017-11-27            NaN
16001 2017-11-27            NaN
16002 2017-11-28            NaN
16003 2017-11-28            NaN
16004 2017-11-29            NaN
16005 2017-11-29            NaN
16006 2017-11-30            NaN
16007 2017-11-30            NaN
16008 2017-12-01            NaN
16009 2017-12-01            NaN
16010 2017-12-02            NaN
16011 2017-12-02            NaN
16012 2017-12-03            NaN
16013 2017-12-03            NaN
16014 2017-12-04            NaN
16015 2017-12-04            NaN
16016 2017-12-05            NaN
16017 2017-12-05            NaN
16018 2017-12-06            NaN
16019 2017-12-06            NaN
16020 2017-12-07            NaN
16021 2017-12-07            NaN
16022 2017-12-08            NaN
16023 2017-12-08            NaN
16024 2017-12-09            NaN
16025 2017-12-09            NaN
16026 2017-12-10            NaN
16027 2017-12-10            NaN
16028 2017-12-11            NaN
16029 2017-12-11            NaN
16030 2017-12-12            NaN
16031 2017-12-12            NaN
16032 2017-12-13            NaN
16033 2017-12-13            NaN
16034 2017-12-14            NaN
16035 2017-12-14            NaN
16036 2017-12-15            NaN
16037 2017-12-15            NaN
16038 2017-12-16            NaN
16039 2017-12-16            NaN
16040 2017-12-17            NaN
16041 2017-12-17            NaN
16042 2017-12-18            NaN
16043 2017-12-18            NaN
16044 2017-12-19            NaN
16045 2017-12-19            NaN
16046 2017-12-20            NaN
16047 2017-12-20            NaN
16048 2017-12-21            NaN
16049 2017-12-21            NaN
16050 2017-12-22            NaN
16051 2017-12-22            NaN
16052 2017-12-23            NaN
16053 2017-12-23            NaN
16054 2017-12-24            NaN
16055 2017-12-24            NaN
16056 2017-12-25            NaN
16057 2017-12-25            NaN
16058 2017-12-26            NaN
16059 2017-12-26            NaN
16060 2017-12-27            NaN
16061 2017-12-27            NaN
16062 2017-12-28            NaN
16063 2017-12-28            NaN
16064 2017-12-29            NaN
16065 2017-12-29            NaN
16066 2017-12-30            NaN
16067 2017-12-30            NaN
16068 2017-12-31            NaN
16069 2017-12-31            NaN

[16070 rows x 2 columns]

In [33]:
import scipy as sp

TypeError: pearsonr() missing 1 required positional argument: 'y'

In [44]:
x,y=pd.merge(canadian_rivers['St_Clair_R'].reset_index(), us_rivers['Detroit_R'].reset_index().rename(columns={'Date':'index'}), on='index').dropna()[['St_Clair_R', 'Detroit_R']].values.T

In [46]:
sp.stats.pearsonr(x,y)

(0.8201879886783383, 0.0)